### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by mcandre** [MasterRoot24/rake-completion#1]
I can use other completion scripts from Homebrew, like docker-completion. But for some reason, rake-completion doesn't appear to do anything when I try to tab complete my Rakefile task names.

Example Rakefile project:

https://github.com/mcandre/rb-ios7crypt

**Comment by JoeNyland** [comment]
Hey @mcandre 

It looks like the Rakefile in that repo doesn't have any [descriptions](https://ruby-doc.org/stdlib-2.2.1/libdoc/rake/rdoc/Rake/DSL.html#method-i-desc) for the tasks.

The completion scripts uses uses the output from `rake --tasks` and if a task doesn't have a description it doesn't show up in the output, so the completion script can't generate a completion option for it.

```diff
diff --git a/Rakefile b/Rakefile
index f873892..bf81834 100644
--- a/Rakefile
+++ b/Rakefile
@@ -1,5 +1,6 @@
 task :default => 'test'
 
+desc 'Build the gem'
 task :gem => 'ios7crypt.gemspec' do
     sh 'gem build *.gemspec'
 end
```

If I make the above change, `rake [tab]` will complete to `rake gem`. So, I'd recommend you add some descriptions to your Rake tasks 🙂 

I hope this helps!

**Comment by mcandre** [comment]
Today I learned about `rake --tasks` :)

Is there a way to query all tasks, even those that do not have descriptions? For many tasks, the name is offen indicative enough of what the task does, that providing a description would be redundant.

**Comment by JoeNyland** [comment]
According to a quick Google, `rake --all` will show all Rake tasks, regardless of whether they have a description or not.
